Repository Mohit5Upadhyay/realTimeTrackingApplication, pull requests merged in 2024-10, with the labels that each got.

#12 SUCCESSFULLY ENHANCED OR UPDATED THE USER INTERFACE OF THE APPLICATION
  app.js
  package.json
  public/css/style.css
  public/js/script.js
  views/index.html
Labels: hacktoberfest, gssoc'24-extd

#25 SUCCESSFULLY INTEGRATED THE USER REGISTRATION AND LOGIN PAGE TO THE WEBSITE
  app.js
  public/assets/Sign up-tracive register.svg
  public/assets/login main.svg
  public/css/login.css
  public/css/register.css
  public/html/contact.html
  public/html/login.html
  public/html/register.html
  public/js/login.js
  public/js/register.js
  public/js/script.js
  views/index.html
Labels: hacktoberfest, gssoc'24-extd, hactoberfest accepted

#40 ✨added chatbot ✨
  views/i.ejs
  views/index.html
Labels: gssoc-ext, level2

#42 Add Responsive Navigation with Hamburger Menu
  public/css/style.css
  views/index.html
Labels: hacktoberfest-accepted
